version: '2.1'

services:
  dictionaries:
    image: ${IMAGE_TAG}
    container_name: dictionaries
    restart: unless-stopped
    # security_opt:
    #   - no-new-privileges:true
    # deploy:
    #   mode: replicated
    #   replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dictionaries-router.entrypoints=websecure"
      - "traefik.http.routers.dictionaries-router.tls=true"
      - "traefik.http.routers.dictionaries-router.rule=(Host(`develop.webapi.dc1.local`) || Host(`webapi.dc1.local`)) && PathPrefix(`/api/${API_VERSION}/dictionaries`)"
      - "traefik.http.middlewares.dictionaries-stripprefix.stripprefix.prefixes=/api/${API_VERSION}/dictionaries/,/api/${API_VERSION}/dictionaries"
      - "traefik.http.middlewares.dictionaries-stripprefix.stripprefix.forceSlash=true"
      - "traefik.http.routers.dictionaries-router.middlewares=dictionaries-stripprefix"

networks:
  default:
    name: net
    external: true
